### ISSUE TITLE
Announce PyConf Hyderabad 2025 on Social Media

### ISSUE THREAD

**Issue by RajatRajdeep** [HydPy/pyconfhyd25-tasks#1]
Share an announcement about PyConf Hyderabad 2025 on all official PyConf Hyderabad social media channels, including the website link: https://2025.pyconfhyd.org/.

**Comment by kalyan678** [comment]
@RajatRajdeep - Assign this task to Amritha & Ashok

**Comment by RajatRajdeep** [comment]
Revised plan: We'll launch the website alongside the CFP announcement.
